{% set name = "schedview" %}
{% set version = "0.19.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/schedview-{{ version }}.tar.gz
  sha256: b77f3dd9fbbd92b34d27f3a8266ddf5a3b0af2e3058d575b82dbf3a0720be50d

build:
  entry_points:
    - prenight = schedview.app.prenight.prenight:main
    - scheduler_dashboard = schedview.app.scheduler_dashboard.scheduler_dashboard:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm <8.0
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base >=5.3
    - colorcet
    - bokeh >=3.1.1
    - healpy
    - holoviews
    - hvplot
    - matplotlib-base
    - numpy
    - pandas
    - panel >=1.1.0
    - param
    - pytz
    - pyyaml
    - skyproj
    - rubin-scheduler >=3.11.0
    - rubin-sim >=2.2.4
    - uranography >=1.2.1

test:
  imports:
    - schedview

about:
  home: https://github.com/lsst/schedview
  summary: Tools for visualization of Rubin Observatory's scheduler status, strategy and progress on LSST.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYRIGHT
  doc_url: https://schedview.lsst.io/
  dev_url: https://github.com/lsst/schedview


extra:
  recipe-maintainers:
    - rhiannonlynne
    - ehneilsen
